# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ycc/Geant4/Carbon_sim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ycc/Geant4/Carbon_sim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ycc/Geant4/Carbon_sim/CMakeFiles /home/ycc/Geant4/Carbon_sim//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ycc/Geant4/Carbon_sim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named detectorSim

# Build rule for target.
detectorSim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 detectorSim
.PHONY : detectorSim

# fast build rule for target.
detectorSim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/build
.PHONY : detectorSim/fast

#=============================================================================
# Target rules for targets named detSim

# Build rule for target.
detSim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 detSim
.PHONY : detSim

# fast build rule for target.
detSim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detSim.dir/build.make CMakeFiles/detSim.dir/build
.PHONY : detSim/fast

detectorSim.o: detectorSim.cc.o
.PHONY : detectorSim.o

# target to build an object file
detectorSim.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/detectorSim.cc.o
.PHONY : detectorSim.cc.o

detectorSim.i: detectorSim.cc.i
.PHONY : detectorSim.i

# target to preprocess a source file
detectorSim.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/detectorSim.cc.i
.PHONY : detectorSim.cc.i

detectorSim.s: detectorSim.cc.s
.PHONY : detectorSim.s

# target to generate assembly for a file
detectorSim.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/detectorSim.cc.s
.PHONY : detectorSim.cc.s

src/ActionInitialization.o: src/ActionInitialization.cc.o
.PHONY : src/ActionInitialization.o

# target to build an object file
src/ActionInitialization.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/src/ActionInitialization.cc.o
.PHONY : src/ActionInitialization.cc.o

src/ActionInitialization.i: src/ActionInitialization.cc.i
.PHONY : src/ActionInitialization.i

# target to preprocess a source file
src/ActionInitialization.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/src/ActionInitialization.cc.i
.PHONY : src/ActionInitialization.cc.i

src/ActionInitialization.s: src/ActionInitialization.cc.s
.PHONY : src/ActionInitialization.s

# target to generate assembly for a file
src/ActionInitialization.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/src/ActionInitialization.cc.s
.PHONY : src/ActionInitialization.cc.s

src/DetectorConstruction.o: src/DetectorConstruction.cc.o
.PHONY : src/DetectorConstruction.o

# target to build an object file
src/DetectorConstruction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/src/DetectorConstruction.cc.o
.PHONY : src/DetectorConstruction.cc.o

src/DetectorConstruction.i: src/DetectorConstruction.cc.i
.PHONY : src/DetectorConstruction.i

# target to preprocess a source file
src/DetectorConstruction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/src/DetectorConstruction.cc.i
.PHONY : src/DetectorConstruction.cc.i

src/DetectorConstruction.s: src/DetectorConstruction.cc.s
.PHONY : src/DetectorConstruction.s

# target to generate assembly for a file
src/DetectorConstruction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/src/DetectorConstruction.cc.s
.PHONY : src/DetectorConstruction.cc.s

src/PhysicsList.o: src/PhysicsList.cc.o
.PHONY : src/PhysicsList.o

# target to build an object file
src/PhysicsList.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/src/PhysicsList.cc.o
.PHONY : src/PhysicsList.cc.o

src/PhysicsList.i: src/PhysicsList.cc.i
.PHONY : src/PhysicsList.i

# target to preprocess a source file
src/PhysicsList.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/src/PhysicsList.cc.i
.PHONY : src/PhysicsList.cc.i

src/PhysicsList.s: src/PhysicsList.cc.s
.PHONY : src/PhysicsList.s

# target to generate assembly for a file
src/PhysicsList.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/src/PhysicsList.cc.s
.PHONY : src/PhysicsList.cc.s

src/PrimaryGeneratorAction.o: src/PrimaryGeneratorAction.cc.o
.PHONY : src/PrimaryGeneratorAction.o

# target to build an object file
src/PrimaryGeneratorAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/src/PrimaryGeneratorAction.cc.o
.PHONY : src/PrimaryGeneratorAction.cc.o

src/PrimaryGeneratorAction.i: src/PrimaryGeneratorAction.cc.i
.PHONY : src/PrimaryGeneratorAction.i

# target to preprocess a source file
src/PrimaryGeneratorAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/src/PrimaryGeneratorAction.cc.i
.PHONY : src/PrimaryGeneratorAction.cc.i

src/PrimaryGeneratorAction.s: src/PrimaryGeneratorAction.cc.s
.PHONY : src/PrimaryGeneratorAction.s

# target to generate assembly for a file
src/PrimaryGeneratorAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/src/PrimaryGeneratorAction.cc.s
.PHONY : src/PrimaryGeneratorAction.cc.s

src/Run.o: src/Run.cc.o
.PHONY : src/Run.o

# target to build an object file
src/Run.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/src/Run.cc.o
.PHONY : src/Run.cc.o

src/Run.i: src/Run.cc.i
.PHONY : src/Run.i

# target to preprocess a source file
src/Run.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/src/Run.cc.i
.PHONY : src/Run.cc.i

src/Run.s: src/Run.cc.s
.PHONY : src/Run.s

# target to generate assembly for a file
src/Run.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/src/Run.cc.s
.PHONY : src/Run.cc.s

src/RunAction.o: src/RunAction.cc.o
.PHONY : src/RunAction.o

# target to build an object file
src/RunAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/src/RunAction.cc.o
.PHONY : src/RunAction.cc.o

src/RunAction.i: src/RunAction.cc.i
.PHONY : src/RunAction.i

# target to preprocess a source file
src/RunAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/src/RunAction.cc.i
.PHONY : src/RunAction.cc.i

src/RunAction.s: src/RunAction.cc.s
.PHONY : src/RunAction.s

# target to generate assembly for a file
src/RunAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/src/RunAction.cc.s
.PHONY : src/RunAction.cc.s

src/SDHit.o: src/SDHit.cc.o
.PHONY : src/SDHit.o

# target to build an object file
src/SDHit.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/src/SDHit.cc.o
.PHONY : src/SDHit.cc.o

src/SDHit.i: src/SDHit.cc.i
.PHONY : src/SDHit.i

# target to preprocess a source file
src/SDHit.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/src/SDHit.cc.i
.PHONY : src/SDHit.cc.i

src/SDHit.s: src/SDHit.cc.s
.PHONY : src/SDHit.s

# target to generate assembly for a file
src/SDHit.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/src/SDHit.cc.s
.PHONY : src/SDHit.cc.s

src/SensitiveDetector.o: src/SensitiveDetector.cc.o
.PHONY : src/SensitiveDetector.o

# target to build an object file
src/SensitiveDetector.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/src/SensitiveDetector.cc.o
.PHONY : src/SensitiveDetector.cc.o

src/SensitiveDetector.i: src/SensitiveDetector.cc.i
.PHONY : src/SensitiveDetector.i

# target to preprocess a source file
src/SensitiveDetector.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/src/SensitiveDetector.cc.i
.PHONY : src/SensitiveDetector.cc.i

src/SensitiveDetector.s: src/SensitiveDetector.cc.s
.PHONY : src/SensitiveDetector.s

# target to generate assembly for a file
src/SensitiveDetector.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detectorSim.dir/build.make CMakeFiles/detectorSim.dir/src/SensitiveDetector.cc.s
.PHONY : src/SensitiveDetector.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... detSim"
	@echo "... detectorSim"
	@echo "... detectorSim.o"
	@echo "... detectorSim.i"
	@echo "... detectorSim.s"
	@echo "... src/ActionInitialization.o"
	@echo "... src/ActionInitialization.i"
	@echo "... src/ActionInitialization.s"
	@echo "... src/DetectorConstruction.o"
	@echo "... src/DetectorConstruction.i"
	@echo "... src/DetectorConstruction.s"
	@echo "... src/PhysicsList.o"
	@echo "... src/PhysicsList.i"
	@echo "... src/PhysicsList.s"
	@echo "... src/PrimaryGeneratorAction.o"
	@echo "... src/PrimaryGeneratorAction.i"
	@echo "... src/PrimaryGeneratorAction.s"
	@echo "... src/Run.o"
	@echo "... src/Run.i"
	@echo "... src/Run.s"
	@echo "... src/RunAction.o"
	@echo "... src/RunAction.i"
	@echo "... src/RunAction.s"
	@echo "... src/SDHit.o"
	@echo "... src/SDHit.i"
	@echo "... src/SDHit.s"
	@echo "... src/SensitiveDetector.o"
	@echo "... src/SensitiveDetector.i"
	@echo "... src/SensitiveDetector.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

